# Custom config
app:
  redis:
    host: localhost
    port: 6379
    password: pass
  kafka:
    group:
      orders: orders-group
      productPriceChanges: product-price-changes-group

spring:
  # Security
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${app.auth-server.jwk-set-uri}
          issuer-uri: ${app.auth-server.issuer-uri}

  # Kafka
  kafka:
    producer:
      transaction-id-prefix: tx-basket-
    consumer:
      enable-auto-commit: false

  # Redis
  redis:
    password: ${app.redis.password}
    host: ${app.redis.host}
    port: ${app.redis.port}

  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

# Test refresh config via bus
test:
  name: "Test 19"
  phone: "009"

---
spring:
  config:
    activate:
      on-profile: docker

app:
  redis:
    host: redis
    password: '{cipher}AQACT6GoyRhsNe5S/wO1rQ7YgVJvTnP7EACwFq3wcGhfqJ28pH7//3/BirnmBq5nnriwaYi8Apiy6ttCZpTbCLfYIMTN+7ovAhzNZcJhXVLKcK7Xauq/2fM7mmXnP7QQzt6o00iN05P4mgnNAlwmaBnTodvEaNLUyvW4+VrcwhuUpx83WTDAd/qbR4HkIOiNjzmtIXno2VnRk50+1j8HpSbH7nlpGogDkM0p/KlCuK+mlM9FvjSn96z2awGf/KDwQIkfT6O9qQPxQCC2/3T5qK3D54zQ12048ZYOhj9AQFfx3yaWqxp3etvi27J7G32V9TGU2ZsF72wwfIasP6LKv3cCTx2aoF4HrneGoQEN0Ildt1S/fxFy2VuGeHcPU/NkFio='
