version: "3.8"

networks:
  eshop:
    driver: bridge

services:
  # Applications
  catalog-command:
    image: "catalog-command-service"
    container_name: "catalog-command"
    ports:
      - 9003:9003
      - 8003:8003
    environment:
      - SERVER_PORT=9003
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8003
      - SPRING_KEYCLOAK_SERVER_URL=http://eshop-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080
      - MONGO_USER=user
      - MONGO_PASSWORD=pass
      - ZIPKIN_HOST=zipkin
    networks:
      - eshop

  catalog-query:
    image: "catalog-query-service"
    container_name: "catalog-query"
    ports:
      - 9004:9004
      - 8004:8004
    environment:
      - SERVER_PORT=9004
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8004
      - SPRING_KEYCLOAK_SERVER_URL=http://eshop-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080
      - MONGO_USER=user
      - MONGO_PASSWORD=pass
      - POSTGRES_USER=dbuser
      - ZIPKIN_HOST=zipkin
    networks:
      - eshop


  gateway:
    image: "gateway-service"
    container_name: "gateway"
    ports:
      - 9000:9000
      - 8000:8000
    environment:
      - SERVER_PORT=9000
      # Buildpacks environment variable to enable debug through a socket on port 8000
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8000
      - ANALYTICS_SERVICE_URL=http://analytics
      - BASKET_SERVICE_URL=http://basket
      - CATALOG_COMMAND_SERVICE_URL=http://catalog-command
      - CATALOG_QUERY_SERVICE_URL=http://catalog-query
      - FLUX_GATEWAY_SERVICE_URL=http://flux-gateway
      - GRAPHQL_GATEWAY_SERVICE_URL=http://graphql-gateway
      - IMAGE_GATEWAY_SERVICE_URL=http://image-gateway
      - ORDER_NOTIFICATIONS_SERVICE_URL=http://order-notifications
      - ORDER_PROCESSING_SERVICE_URL=http://order-processing
      - RATING_SERVICE_URL=http://rating
      - SPRING_REDIS_HOST=gateway-redis
      - SPRING_REDIS_PORT=6380
      - SPRING_KEYCLOAK_SERVER_URL=http://eshop-keycloak:8080
      - SPRING_KEYCLOAK_SERVER_EXTERNAL_URL=http://localhost:8080
    networks:
      - eshop
