dgs:
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    extensions:
      scalars:
        enabled: true
    schema-locations:
      - classpath*:schema/**/*.graphql*
    path: /graphql
    apq:
      enabled: true

logging:
  level:
    root: info
