spring:
  # JPA
  jpa:
    show-sql: false

  # Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration

# Logging
logging:
  level:
    org:
      springframework:
        web: INFO
        security: INFO
    web: INFO
    root: INFO


