version: '3.9'

services:
  minio:
    image: minio/minio:RELEASE.2022-06-20T23-13-45Z
    restart: always
    environment:
      MINIO_ACCESS_KEY: mystorage
      MINIO_SECRET_KEY: mystorage
      MINIO_REGION: eu-east
    ports:
      - "8086:9000"
    volumes:
      - ./minio:/data
    command: server /data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 mystorage mystorage;
      /usr/bin/mc rm -r --force myminio/catalog-images;
      /usr/bin/mc mb myminio/catalog-images;
      /usr/bin/mc policy download myminio/catalog-images;
      exit 0;
      "

  imgproxy:
    image: darthsim/imgproxy:v3.6
    restart: always
    # Mount a volume as local image source
#    volumes:
#      - ./images:/opt # link to minio volume to imgproxy's /opt folder for local filesystem.

    environment:
      IMGPROXY_ALLOW_ORIGIN: '*'
#      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /opt # you can link Minio volume to imgproxy and use as a local filesystem.
      IMGPROXY_USE_S3: 'true'
      IMGPROXY_S3_ENDPOINT: http://minio:9000
      AWS_ACCESS_KEY_ID: mystorage
      AWS_SECRET_ACCESS_KEY: mystorage
      AWS_REGION: eu-east
    links:
      - minio
    ports:
      - "8887:8080"
