version: '3.9'

services:

  catalog-command:
    build: ../services/catalog/catalog-command
    networks:
      - eshopnet
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVICE_USER: ${CONFIG_SERVICE_USER}
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      EUREKA_USER: ${EUREKA_USER}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}

  catalog-query:
    build: ../services/catalog/catalog-query
    networks:
      - eshopnet
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVICE_USER: ${CONFIG_SERVICE_USER}
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      EUREKA_USER: ${EUREKA_USER}
      POSTGRES_USER: ${POSTGRES_USER}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}

  basket:
    build: ../services/basket
    networks:
      - eshopnet
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVICE_USER: ${CONFIG_SERVICE_USER}
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      EUREKA_USER: ${EUREKA_USER}
      POSTGRES_USER: ${POSTGRES_USER}

  order-processing:
    build: ../services/order-processing
    networks:
      - eshopnet
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVICE_USER: ${CONFIG_SERVICE_USER}
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      EUREKA_USER: ${EUREKA_USER}
      POSTGRES_USER: ${POSTGRES_USER}

  payment:
    build: ../services/payment
    networks:
      - eshopnet
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVICE_USER: ${CONFIG_SERVICE_USER}
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      EUREKA_USER: ${EUREKA_USER}
      POSTGRES_USER: ${POSTGRES_USER}

  order-grace-period-task:
    build: ../services/order-grace-period-task
    networks:
      - eshopnet
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVICE_USER: ${CONFIG_SERVICE_USER}
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      EUREKA_USER: ${EUREKA_USER}
      POSTGRES_USER: ${POSTGRES_USER}
    depends_on:
      - order-processing

  order-notifications:
    build: ../services/order-notifications
    networks:
      - eshopnet
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVICE_USER: ${CONFIG_SERVICE_USER}
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      EUREKA_USER: ${EUREKA_USER}
      POSTGRES_USER: ${POSTGRES_USER}

  analytics:
    build: ../services/analytics
    networks:
      - eshopnet
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVICE_USER: ${CONFIG_SERVICE_USER}
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      EUREKA_USER: ${EUREKA_USER}
      POSTGRES_USER: ${POSTGRES_USER}

  rating:
    build: ../services/rating
    networks:
      - eshopnet
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVICE_USER: ${CONFIG_SERVICE_USER}
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      EUREKA_USER: ${EUREKA_USER}
      POSTGRES_USER: ${POSTGRES_USER}

networks:
  eshopnet:
    driver: bridge
