version: '3.9'

services:
  zipkin:
    image: openzipkin/zipkin:2.23.2
    networks:
      - eshopnet
    ports:
      - 9411:9411
    restart: on-failure
    environment:
      STORAGE_TYPE: mem
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      - kafka
