spring:
  # JPA
  jpa:
    show-sql: false

  # Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration

# Logging
logging:
  level:
    org:
      springframework:
        web: INFO
        security: INFO
    web: INFO
    root: INFO

---
spring:
  config:
    activate:
      on-profile: dev

  # JPA
  jpa:
    show-sql: false

  flyway:
    locations: classpath:db/migration, classpath:db/testdata

---
spring:
  config:
    activate:
      on-profile: docker

  flyway:
    locations: classpath:db/migration, classpath:db/testdata
