spring:
  main:
    allow-circular-references: true

  # JPA
  jpa:
    show-sql: false

  # Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration

# Logging
logging:
  level:
    org:
      springframework:
        web: INFO
        security: INFO
    web: INFO
    root: INFO


